### ISSUE TITLE
getDeclaredField("mDuration") 读取不到 getDeclaredField("mCurrVelocity") 可以

### ISSUE THREAD

**Issue by WU1208** [xmuSistone/PersistentCoordinatorLayout#2]
getDeclaredField("mDuration") 读取不到 反而 getDeclaredField("mCurrVelocity") 可以

导致直接闪退

**Comment by xmuSistone** [comment]
RecyclerView的版本是？你看下源码，我感觉是duration的名字不叫mDuration

**Comment by xmuSistone** [comment]
crash问题已修复，请pull最新代码再试
