### ISSUE TITLE
Android11无法通过反射获取mDuration字段导致闪退

### ISSUE THREAD

**Issue by ozyl** [xmuSistone/PersistentCoordinatorLayout#5]
```

com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:666)
--
......
java.lang.NoSuchFieldException:No field mDuration in class Landroid/widget/OverScroller$SplineOverScroller; (declaration of 'android.widget.OverScroller$SplineOverScroller' appears in /system/framework/framework.jar!classes3.dex)
java.lang.Class.getDeclaredField(Native Method)
java.lang.reflect.Method.invoke(Native Method)
```

**Comment by xmuSistone** [comment]
触发了私有api访问，这个问题之前已经修过了！我试了Android 11是没问题的

**Comment by ozyl** [comment]
demo的targetSdkVersion 30时可以复现

**Comment by appdev** [comment]
Android 11 上确实有问题
![image](https://user-images.githubusercontent.com/9107717/121678083-4fcda500-cae9-11eb-8718-f54c83ce35e9.png)

**Comment by honganxue** [comment]
怎么解决?

**Comment by appdev** [comment]
> 怎么解决?

就换了一个。自己写

**Comment by xmuSistone** [comment]
@appdev @honganxue 这个问题主要是targetSdkVersion较高时，反射获取隐私API失败，导致了crash；

有两种解法可以参考：

- 降低targetSdkVersion，我试了安卓11是没问题的；
- 集成三方库[FreeReflection](https://github.com/tiann/FreeReflection)，亲试有效；
